node {
  stage("Checkout") {
    checkout scm
  }
  stage("Run Tests") {
    sh "common_tests python2.7"
  }
}

node ('python34') {
  stage("Checkout") {
    checkout scm
  }
  stage("Run Tests") {
    sh "common_tests python2.7"
  }
}


