node {
  stage("Checkout") {
    checkout scm
  }
  stage("Build Image") {
    sh "ls -lah | PYTHONPATH=`pwd` python2.7 poline/poline.py -s 'repr(x) for x in _'"
  }
}

node ('python34') {
  stage("Checkout") {
    checkout scm
  }
  stage("Build Image") {
    sh "ls -lah | PYTHONPATH=`pwd` python3.4 poline/poline.py -s 'repr(x) for x in _'"
  }
}


